name: tests-build

on:
  pull_request:
    branches:
    - main
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - uses: actions/checkout@v3
      - run: cd common-base-module && mvn clean install
      - uses: actions/checkout@v3
      - run: cd cs544-202403-project && mvn clean install
